# Generated by Django 5.1.4 on 2024-12-20 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkplaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('details_page_url', models.URLField(max_length=500)),
                ('company_page_url', models.URLField(max_length=500)),
                ('company_logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('company_logo_url_optimized', models.URLField(blank=True, max_length=500, null=True)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('client_brand_id', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=255)),
                ('employment_type', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('job_id', models.CharField(max_length=32)),
                ('score', models.FloatField(blank=True, null=True)),
                ('easy_apply', models.BooleanField(default=False)),
                ('willing_to_sponsor', models.BooleanField(default=False)),
                ('employer_type', models.CharField(max_length=50)),
                ('work_from_home_availability', models.BooleanField(default=False)),
                ('is_remote', models.BooleanField(default=False)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('guid', models.CharField(max_length=36)),
                ('workplace_types', models.ManyToManyField(blank=True, to='api.workplacetype')),
            ],
        ),
    ]
