# Generated by Django 5.1.4 on 2024-12-20 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='workplace_types',
        ),
        migrations.AddField(
            model_name='job',
            name='workplace_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.workplacetype'),
        ),
    ]
