# Generated by Django 5.1.4 on 2024-12-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_job_workplace_types_job_workplace_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='workplace_types',
        ),
        migrations.AddField(
            model_name='job',
            name='workplace_types',
            field=models.ManyToManyField(blank=True, to='api.workplacetype'),
        ),
    ]
